# Generated by Django 2.2.6 on 2020-06-18 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('topic', models.TextField()),
                ('date_topiced', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
