# Generated by Django 3.0.8 on 2020-07-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatedetail',
            old_name='post',
            new_name='detail',
        ),
    ]
