# Generated by Django 2.2.6 on 2020-06-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200619_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='postcontent',
            name='headline',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='headline',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
