# Generated by Django 2.2.6 on 2020-06-20 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200619_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontent',
            name='target',
        ),
        migrations.AddField(
            model_name='post',
            name='postcontent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.PostContent'),
        ),
    ]
