# Generated by Django 2.2.6 on 2020-06-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200620_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postcontent',
        ),
        migrations.AddField(
            model_name='post',
            name='postcontent',
            field=models.ManyToManyField(to='blog.PostContent'),
        ),
    ]
